In [2]:
!pip install numpy
import numpy as np


[notice] A new release of pip is available: 25.1.1 -> 25.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [3]:
my_list = [10,20,30,40]

In [4]:
type(my_list)

list

In [5]:
np.array(my_list)

array([10, 20, 30, 40])

In [6]:
my_numpy_array = np.array(my_list)

In [7]:
type(my_numpy_array)

numpy.ndarray

In [9]:
print(my_numpy_array.max())

40


In [10]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [11]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [13]:
np.random.random(4)

array([0.148005  , 0.174293  , 0.47435545, 0.6473382 ])

In [16]:
my_list1 = [1,2]

In [17]:
my_list2 = [2,3]

In [18]:
my_list1+my_list2

[1, 2, 2, 3]

In [20]:
my_numpy_array1 = np.array(my_list1)

In [23]:
my_numpy_array2 = np.array(my_list2)

In [24]:
my_numpy_array1 + my_numpy_array2

array([3, 5])

In [25]:
my_numpy_array1 * my_numpy_array2

array([2, 6])

In [26]:
my_numpy_array1 - my_numpy_array2

array([-1, -1])

In [27]:
my_numpy_array1 / my_numpy_array2

array([0.5       , 0.66666667])

In [28]:
my_numpy_array1 *5

array([ 5, 10])

In [29]:
my_list1 *5

[1, 2, 1, 2, 1, 2, 1, 2, 1, 2]

In [30]:
other_array = np.array([10,20,30,40])

In [33]:
print(other_array.max())

40


In [34]:
print(other_array.sum())

100


In [35]:
my_numpy_array1

array([1, 2])

In [36]:
other_array

array([10, 20, 30, 40])

In [39]:
#my_numpy_array1 + other_array #same number array!

In [40]:
# arange & indexing

In [41]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [42]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [43]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [44]:
np_array = np.arange(0,10)

In [45]:
np_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [46]:
np_array[0]

np.int64(0)

In [47]:
np_array[-1]

np.int64(9)

In [48]:
np_array[1:4:]

array([1, 2, 3])

In [49]:
np_array[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [50]:
np_array[2:6:2]

array([2, 4])

In [51]:
# random

In [52]:
np.random.randn(4)

array([-1.95966867, -0.20954108, -0.33899074,  0.44896796])

In [53]:
np.random.randn(4,4)

array([[ 1.00503687, -0.74046056,  1.01824829, -0.57891535],
       [-0.16572519,  0.49621117, -0.70928595,  0.65702921],
       [ 1.18506309, -2.08405472, -0.18243986,  0.57101174],
       [-0.9749852 ,  0.84748521,  2.16524638,  0.68976727]])

In [56]:
np.random.randint(1,300,5)

array([258,  54, 252,   4,  53], dtype=int32)