In [3]:
import pandas as pd
import numpy as np

In [4]:
data = np.random.randn(4,3)

In [8]:
print(data)

[[-0.32872683  0.41948725 -0.14549809]
 [ 1.33959372  1.06333002 -0.05195317]
 [ 0.34380155  0.88480483 -0.42843897]
 [-1.66209332  0.34511278 -0.22851682]]


In [6]:
data_frame = pd.DataFrame(data)

In [7]:
data_frame

0         1         2
0 -0.328727  0.419487 -0.145498
1  1.339594  1.063330 -0.051953
2  0.343802  0.884805 -0.428439
3 -1.662093  0.345113 -0.228517

In [9]:
type(data_frame)

pandas.core.frame.DataFrame

In [11]:
type(data_frame[0])

pandas.core.series.Series

In [12]:
new_df = pd.DataFrame(data, index = ["Mami", "Zeynep", "Atlas", "Ali"], columns= ["Salary", "Age", "Seniority"])

In [13]:
new_df

Salary       Age  Seniority
Mami   -0.328727  0.419487  -0.145498
Zeynep  1.339594  1.063330  -0.051953
Atlas   0.343802  0.884805  -0.428439
Ali    -1.662093  0.345113  -0.228517

In [14]:
new_df["Age"]

Mami      0.419487
Zeynep    1.063330
Atlas     0.884805
Ali       0.345113
Name: Age, dtype: float64

In [15]:
new_df[["Salary","Age"]]

Salary       Age
Mami   -0.328727  0.419487
Zeynep  1.339594  1.063330
Atlas   0.343802  0.884805
Ali    -1.662093  0.345113

In [16]:
new_df.loc["Mami"]

Salary      -0.328727
Age          0.419487
Seniority   -0.145498
Name: Mami, dtype: float64

In [17]:
new_df.iloc[0]

Salary      -0.328727
Age          0.419487
Seniority   -0.145498
Name: Mami, dtype: float64

In [19]:
new_df.iloc[:,0]

Mami     -0.328727
Zeynep    1.339594
Atlas     0.343802
Ali      -1.662093
Name: Salary, dtype: float64

In [20]:
new_df["Extra"] = 10

In [21]:
new_df

Salary       Age  Seniority  Extra
Mami   -0.328727  0.419487  -0.145498     10
Zeynep  1.339594  1.063330  -0.051953     10
Atlas   0.343802  0.884805  -0.428439     10
Ali    -1.662093  0.345113  -0.228517     10

In [23]:
new_df.drop("Extra", axis = 1)

Salary       Age  Seniority
Mami   -0.328727  0.419487  -0.145498
Zeynep  1.339594  1.063330  -0.051953
Atlas   0.343802  0.884805  -0.428439
Ali    -1.662093  0.345113  -0.228517

In [24]:
new_df

Salary       Age  Seniority  Extra
Mami   -0.328727  0.419487  -0.145498     10
Zeynep  1.339594  1.063330  -0.051953     10
Atlas   0.343802  0.884805  -0.428439     10
Ali    -1.662093  0.345113  -0.228517     10

In [28]:
#new_df.drop("Extra", axis = 1, inplace = True)

In [29]:
new_df

Salary       Age  Seniority
Mami   -0.328727  0.419487  -0.145498
Zeynep  1.339594  1.063330  -0.051953
Atlas   0.343802  0.884805  -0.428439
Ali    -1.662093  0.345113  -0.228517

In [30]:
new_df["Mehmet"] = 10

In [31]:
new_df

Salary       Age  Seniority  Mehmet
Mami   -0.328727  0.419487  -0.145498      10
Zeynep  1.339594  1.063330  -0.051953      10
Atlas   0.343802  0.884805  -0.428439      10
Ali    -1.662093  0.345113  -0.228517      10

In [32]:
new_df.drop("Mehmet", axis = 1, inplace = True)
new_df

Salary       Age  Seniority
Mami   -0.328727  0.419487  -0.145498
Zeynep  1.339594  1.063330  -0.051953
Atlas   0.343802  0.884805  -0.428439
Ali    -1.662093  0.345113  -0.228517

In [33]:
new_df["Ali"] = 10

In [34]:
new_df

Salary       Age  Seniority  Ali
Mami   -0.328727  0.419487  -0.145498   10
Zeynep  1.339594  1.063330  -0.051953   10
Atlas   0.343802  0.884805  -0.428439   10
Ali    -1.662093  0.345113  -0.228517   10

In [35]:
new_df.drop("Ali")

Salary       Age  Seniority  Ali
Mami   -0.328727  0.419487  -0.145498   10
Zeynep  1.339594  1.063330  -0.051953   10
Atlas   0.343802  0.884805  -0.428439   10

In [36]:
new_df

Salary       Age  Seniority  Ali
Mami   -0.328727  0.419487  -0.145498   10
Zeynep  1.339594  1.063330  -0.051953   10
Atlas   0.343802  0.884805  -0.428439   10
Ali    -1.662093  0.345113  -0.228517   10

In [37]:
new_df.drop("Ali", axis = 1, inplace = True)
new_df

Salary       Age  Seniority
Mami   -0.328727  0.419487  -0.145498
Zeynep  1.339594  1.063330  -0.051953
Atlas   0.343802  0.884805  -0.428439
Ali    -1.662093  0.345113  -0.228517

In [38]:
new_df.drop("Ali", axis = 0)

Salary       Age  Seniority
Mami   -0.328727  0.419487  -0.145498
Zeynep  1.339594  1.063330  -0.051953
Atlas   0.343802  0.884805  -0.428439

In [39]:
new_df

Salary       Age  Seniority
Mami   -0.328727  0.419487  -0.145498
Zeynep  1.339594  1.063330  -0.051953
Atlas   0.343802  0.884805  -0.428439
Ali    -1.662093  0.345113  -0.228517

In [40]:
new_df.loc["Mami"]

Salary      -0.328727
Age          0.419487
Seniority   -0.145498
Name: Mami, dtype: float64

In [41]:
new_df.loc["Mami"]["Salary"]

np.float64(-0.32872682999830977)

In [42]:
new_df.loc["Mami","Salary"]

np.float64(-0.32872682999830977)

In [43]:
new_df.loc["Mami","Salary"] = 100

In [44]:
new_df

Salary       Age  Seniority
Mami    100.000000  0.419487  -0.145498
Zeynep    1.339594  1.063330  -0.051953
Atlas     0.343802  0.884805  -0.428439
Ali      -1.662093  0.345113  -0.228517

In [45]:
new_df > 0

Salary   Age  Seniority
Mami      True  True      False
Zeynep    True  True      False
Atlas     True  True      False
Ali      False  True      False

In [46]:
boolean_frame = new_df > 0

In [47]:
new_df[boolean_frame]

Salary       Age  Seniority
Mami    100.000000  0.419487        NaN
Zeynep    1.339594  1.063330        NaN
Atlas     0.343802  0.884805        NaN
Ali            NaN  0.345113        NaN

In [48]:
new_df[new_df> 0]

Salary       Age  Seniority
Mami    100.000000  0.419487        NaN
Zeynep    1.339594  1.063330        NaN
Atlas     0.343802  0.884805        NaN
Ali            NaN  0.345113        NaN

In [49]:
new_df[new_df["Salary"]>1]

Salary       Age  Seniority
Mami    100.000000  0.419487  -0.145498
Zeynep    1.339594  1.063330  -0.051953

In [51]:
new_df[new_df["Age"]<1]

Salary       Age  Seniority
Mami   100.000000  0.419487  -0.145498
Atlas    0.343802  0.884805  -0.428439
Ali     -1.662093  0.345113  -0.228517

In [52]:
new_df

Salary       Age  Seniority
Mami    100.000000  0.419487  -0.145498
Zeynep    1.339594  1.063330  -0.051953
Atlas     0.343802  0.884805  -0.428439
Ali      -1.662093  0.345113  -0.228517

In [53]:
new_df.reset_index()

index      Salary       Age  Seniority
0    Mami  100.000000  0.419487  -0.145498
1  Zeynep    1.339594  1.063330  -0.051953
2   Atlas    0.343802  0.884805  -0.428439
3     Ali   -1.662093  0.345113  -0.228517

In [54]:
new_df

Salary       Age  Seniority
Mami    100.000000  0.419487  -0.145498
Zeynep    1.339594  1.063330  -0.051953
Atlas     0.343802  0.884805  -0.428439
Ali      -1.662093  0.345113  -0.228517

In [55]:
reset_frame = new_df.reset_index()

In [56]:
reset_frame

index      Salary       Age  Seniority
0    Mami  100.000000  0.419487  -0.145498
1  Zeynep    1.339594  1.063330  -0.051953
2   Atlas    0.343802  0.884805  -0.428439
3     Ali   -1.662093  0.345113  -0.228517

In [57]:
reset_frame.loc[0]

index            Mami
Salary          100.0
Age          0.419487
Seniority   -0.145498
Name: 0, dtype: object

In [58]:
new_indices = ["Mam","Zey","Atlas","Al"]

In [60]:
new_df["NewIndex"] = new_indices

In [61]:
new_df

Salary       Age  Seniority NewIndex
Mami    100.000000  0.419487  -0.145498      Mam
Zeynep    1.339594  1.063330  -0.051953      Zey
Atlas     0.343802  0.884805  -0.428439    Atlas
Ali      -1.662093  0.345113  -0.228517       Al

In [62]:
new_df.set_index("NewIndex", inplace=True)

In [63]:
new_df

Salary       Age  Seniority
NewIndex                                 
Mam       100.000000  0.419487  -0.145498
Zey         1.339594  1.063330  -0.051953
Atlas       0.343802  0.884805  -0.428439
Al         -1.662093  0.345113  -0.228517

In [65]:
new_df.loc["Zey"]

Salary       1.339594
Age          1.063330
Seniority   -0.051953
Name: Zey, dtype: float64

In [66]:
# multi index

In [67]:
first_index = ["Simpson","Simpson","Simpson","South Park","South Park","South Park"]

In [68]:
inner_index = ["Homer", "Bart", "Marge", "Cartman", "Kenny", "Kyle"]

In [69]:
zipped_index = list(zip(first_index, inner_index))

In [70]:
zipped_index

[('Simpson', 'Homer'),
 ('Simpson', 'Bart'),
 ('Simpson', 'Marge'),
 ('South Park', 'Cartman'),
 ('South Park', 'Kenny'),
 ('South Park', 'Kyle')]

In [71]:
zipped_index = pd.MultiIndex.from_tuples(zipped_index)

In [72]:
zipped_index

MultiIndex([(   'Simpson',   'Homer'),
            (   'Simpson',    'Bart'),
            (   'Simpson',   'Marge'),
            ('South Park', 'Cartman'),
            ('South Park',   'Kenny'),
            ('South Park',    'Kyle')],
           )

In [73]:
sample_values = np.ones((6,2))

In [74]:
big_df = pd.DataFrame(sample_values, index = zipped_index, columns=["Age", "Salary"])

In [75]:
big_df

Age  Salary
Simpson    Homer    1.0     1.0
           Bart     1.0     1.0
           Marge    1.0     1.0
South Park Cartman  1.0     1.0
           Kenny    1.0     1.0
           Kyle     1.0     1.0

In [76]:
big_df["Age"]

Simpson     Homer      1.0
            Bart       1.0
            Marge      1.0
South Park  Cartman    1.0
            Kenny      1.0
            Kyle       1.0
Name: Age, dtype: float64

In [78]:
big_df.loc["Simpson"]

Age  Salary
Homer  1.0     1.0
Bart   1.0     1.0
Marge  1.0     1.0

In [79]:
big_df.loc["Simpson"].loc["Homer"]

Age       1.0
Salary    1.0
Name: Homer, dtype: float64