In [1]:
import numpy as np

In [2]:
new_array = np.random.randint(1,100,20)

In [3]:
new_array

array([45, 25,  3, 46, 97, 85, 96, 43, 86, 98, 73, 35, 91, 32, 26, 20, 49,
       14, 83,  5], dtype=int32)

In [4]:
new_array > 25

array([ True, False, False,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True, False,  True, False,
        True, False])

In [5]:
new_array[new_array > 25]

array([45, 46, 97, 85, 96, 43, 86, 98, 73, 35, 91, 32, 26, 49, 83],
      dtype=int32)

In [6]:
new_array[new_array < 25]

array([ 3, 20, 14,  5], dtype=int32)

In [7]:
# transpose & reshape

In [10]:
matrix_array = np.array([[10,20],[20,30],[30,40]])

In [11]:
matrix_array

array([[10, 20],
       [20, 30],
       [30, 40]])

In [12]:
matrix_array.shape

(3, 2)

In [13]:
matrix_array.transpose()

array([[10, 20, 30],
       [20, 30, 40]])

In [14]:
matrix_array.T

array([[10, 20, 30],
       [20, 30, 40]])

In [15]:
random_array = np.random.random((6,1))

In [16]:
random_array

array([[0.93242111],
       [0.521996  ],
       [0.74730936],
       [0.69074985],
       [0.17343144],
       [0.48853252]])

In [17]:
random_array.shape

(6, 1)

In [18]:
random_array.reshape(2,3)

array([[0.93242111, 0.521996  , 0.74730936],
       [0.69074985, 0.17343144, 0.48853252]])

In [19]:
random_array.reshape(3,2)

array([[0.93242111, 0.521996  ],
       [0.74730936, 0.69074985],
       [0.17343144, 0.48853252]])

In [20]:
# z-score

In [21]:
data = np.array([10,12,13,15,18,25,100,105])

In [22]:
#outlier

In [23]:
mean = np.mean(data)

In [24]:
mean

np.float64(37.25)

In [25]:
data.sum()/len(data)

np.float64(37.25)

In [26]:
std = np.std(data)

In [27]:
std

np.float64(37.9333296719389)

In [31]:
z_scores = (data -mean) / std

In [32]:
z_scores

array([-0.71836562, -0.66564154, -0.6392795 , -0.58655542, -0.50746929,
       -0.322935  ,  1.65421809,  1.78602829])

In [34]:
z_scores[z_scores > 1]

array([1.65421809, 1.78602829])

In [35]:
data[z_scores > 1]

array([100, 105])

In [38]:
#2x+3y = 8 5x+7y = 19

In [40]:
#coefficiant
A = np.array([[2,3],[5,7]])

In [41]:
#constant
b = np.array([8,19])

In [42]:
solution = np.linalg.solve(A,b)

In [43]:
solution

array([1., 2.])