In [1]:
import numpy as np

In [2]:
my_matrix = [[5,10], [15,20]]

In [3]:
my_matrix[0]

[5, 10]

In [4]:
my_matrix[1]

[15, 20]

In [5]:
my_matrix[0][0]

5

In [6]:
numpy_matrix = np.array([[5,10], [15,20]])

In [8]:
numpy_matrix

array([[ 5, 10],
       [15, 20]])

In [9]:
numpy_matrix.sum()

np.int64(50)

In [11]:
np.ones((4,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [12]:
np.zeros((5,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [13]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [14]:
np.random.random((3,2))

array([[0.70303651, 0.2173007 ],
       [0.9380222 , 0.0162981 ],
       [0.18825076, 0.53989289]])

In [15]:
# matrix arithmetic

In [18]:
first_array = np.array([[10,20],[30,40]])

In [19]:
second_array = np.array([[5,15], [25,35]])

In [20]:
first_array+second_array

array([[15, 35],
       [55, 75]])

In [21]:
first_array

array([[10, 20],
       [30, 40]])

In [22]:
third_array = np.array([[50,60]])

In [23]:
third_array

array([[50, 60]])

In [24]:
first_array+third_array

array([[ 60,  80],
       [ 80, 100]])

In [25]:
fourth_array = np.array([[10,20,30,40,50]])

In [27]:
# first_array+fourth_array

In [28]:
first_array *2

array([[20, 40],
       [60, 80]])

In [29]:
first_array / 4

array([[ 2.5,  5. ],
       [ 7.5, 10. ]])

In [30]:
third_array = np.array([[10],[20]])

In [31]:
third_array

array([[10],
       [20]])

In [32]:
third_array.shape

(2, 1)

In [33]:
first_array.shape

(2, 2)

In [34]:
first_array+third_array

array([[20, 30],
       [50, 60]])

In [35]:
# matrix_multp

In [36]:
first_array

array([[10, 20],
       [30, 40]])

In [37]:
second_array

array([[ 5, 15],
       [25, 35]])

In [38]:
first_array*second_array

array([[  50,  300],
       [ 750, 1400]])

In [39]:
first_matrix = np.array([[10,20,30]])

In [40]:
first_matrix

array([[10, 20, 30]])

In [41]:
first_matrix.shape

(1, 3)

In [43]:
second_matrix = np.array([[2,3],[2,3],[2,3]])

In [44]:
second_matrix

array([[2, 3],
       [2, 3],
       [2, 3]])

In [45]:
second_matrix.shape

(3, 2)

In [47]:
#first_matrix*second_matrix

In [49]:
result_matrix = first_matrix.dot(second_matrix)

In [50]:
result_matrix

array([[120, 180]])

In [51]:
result_matrix.shape

(1, 2)